### ISSUE TITLE
Some problems with usage

### ISSUE THREAD

**Issue by tsapa44** [auxilincom/auxilin-merge#1]
Antons-MBP:bofimu tsapa44$ bash git-merge.sh
=== CLONE REPOSITORY https://github.com/auxilincom/auxilin ===
Cloning into 'auxilin'...
remote: Enumerating objects: 52, done.
remote: Counting objects: 100% (52/52), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 52 (delta 1), reused 49 (delta 1), pack-reused 0
Unpacking objects: 100% (52/52), done.
=== DONE CLONE REPOSITORY https://github.com/auxilincom/auxilin ===
=== PARSE release.yml FILE ===
sed: release.yml: No such file or directory
=== END PARSE FILE ===
sed: 1: "CHANGELOG.md": invalid command code C
sed: 1: "CHANGELOG.md": invalid command code C
sed: 1: "CHANGELOG.md": invalid command code C
sed: 1: "CHANGELOG.md": invalid command code C
sed: 1: "CHANGELOG.md": invalid command code C
sed: 1: "CHANGELOG.md": invalid command code C

**Comment by ezhivitsa** [comment]
The problem was fixed
